//Generated by TurboLink CodeGenerator, do not edit!
#include "SEcsrelay/EcsRelayMessage.h"
#include "SEcsrelay/EcsRelayMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcEcsrelayIdentity, ::ecsrelay::Identity)
DEFINE_JSON_FUNCTIONS(FGrpcEcsrelaySignature, ::ecsrelay::Signature)
DEFINE_JSON_FUNCTIONS(FGrpcEcsrelayMessage, ::ecsrelay::Message)
DEFINE_JSON_FUNCTIONS(FGrpcEcsrelaySubscriptionRequest, ::ecsrelay::SubscriptionRequest)
DEFINE_JSON_FUNCTIONS(FGrpcEcsrelaySubscription, ::ecsrelay::Subscription)
DEFINE_JSON_FUNCTIONS(FGrpcEcsrelayPushRequest, ::ecsrelay::PushRequest)
DEFINE_JSON_FUNCTIONS(FGrpcEcsrelayPushManyRequest, ::ecsrelay::PushManyRequest)
DEFINE_JSON_FUNCTIONS(FGrpcEcsrelayPushResponse, ::ecsrelay::PushResponse)
DEFINE_JSON_FUNCTIONS(FGrpcEcsrelayCountIdentitiesRequest, ::ecsrelay::CountIdentitiesRequest)
DEFINE_JSON_FUNCTIONS(FGrpcEcsrelayCountIdentitiesResponse, ::ecsrelay::CountIdentitiesResponse)
DEFINE_JSON_FUNCTIONS(FGrpcEcsrelayBalanceRequest, ::ecsrelay::BalanceRequest)
DEFINE_JSON_FUNCTIONS(FGrpcEcsrelayBalanceResponse, ::ecsrelay::BalanceResponse)

FGrpcEcsrelaySubscriptionRequest UGrpcEcsrelaySubscriptionRequestHelperLibrary::MakeSubscriptionRequest( 
    FGrpcEcsrelaySignature Signature, FGrpcEcsrelaySubscription Subscription 
)
{
    FGrpcEcsrelaySubscriptionRequest SubscriptionRequest;
    SubscriptionRequest.Signature = Signature;
    SubscriptionRequest.Subscription = MakeShareable(new FGrpcEcsrelaySubscription(Subscription));

    return SubscriptionRequest;
}

void UGrpcEcsrelaySubscriptionRequestHelperLibrary::BreakSubscriptionRequest(const FGrpcEcsrelaySubscriptionRequest& SubscriptionRequest,  
    FGrpcEcsrelaySignature& Signature, FGrpcEcsrelaySubscription& Subscription 
)
{
    Signature = SubscriptionRequest.Signature;
    if(SubscriptionRequest.Subscription.Get()) 
    {
        Subscription = *(SubscriptionRequest.Subscription.Get());
    }
}

