//Generated by TurboLink CodeGenerator, do not edit!
#include "SFaucet/FaucetMessage.h"
#include "SFaucet/FaucetMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcFaucetLinkedTwitterPair, ::faucet::LinkedTwitterPair)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetFaucetStore, ::faucet::FaucetStore)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetDripRequest, ::faucet::DripRequest)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetDripDevRequest, ::faucet::DripDevRequest)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetDripResponse, ::faucet::DripResponse)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetTimeUntilDripResponse, ::faucet::TimeUntilDripResponse)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetGetLinkedTwittersRequest, ::faucet::GetLinkedTwittersRequest)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetGetLinkedTwittersResponse, ::faucet::GetLinkedTwittersResponse)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetLinkedTwitterForAddressRequest, ::faucet::LinkedTwitterForAddressRequest)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetLinkedTwitterForAddressResponse, ::faucet::LinkedTwitterForAddressResponse)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetLinkedAddressForTwitterRequest, ::faucet::LinkedAddressForTwitterRequest)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetLinkedAddressForTwitterResponse, ::faucet::LinkedAddressForTwitterResponse)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetSetLinkedTwitterRequest, ::faucet::SetLinkedTwitterRequest)
DEFINE_JSON_FUNCTIONS(FGrpcFaucetSetLinkedTwitterResponse, ::faucet::SetLinkedTwitterResponse)

