//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SFaucet/FaucetService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "faucet.grpc.pb.h"
#include "FaucetService_Private.generated.h"

class UFaucetService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::faucet::FaucetService::Stub> Stub;
};

UCLASS()
class UFaucetServiceDripLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UFaucetServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetDripResponse& Response);
public:
	FGrpcContextHandle Handle;
	UFaucetService::FDripResponseLambda ResponseLambda;
};

UCLASS()
class UFaucetServiceDripDevLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UFaucetServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetDripResponse& Response);
public:
	FGrpcContextHandle Handle;
	UFaucetService::FDripDevResponseLambda ResponseLambda;
};

UCLASS()
class UFaucetServiceDripVerifyTweetLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UFaucetServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetDripResponse& Response);
public:
	FGrpcContextHandle Handle;
	UFaucetService::FDripVerifyTweetResponseLambda ResponseLambda;
};

UCLASS()
class UFaucetServiceTimeUntilDripLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UFaucetServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetTimeUntilDripResponse& Response);
public:
	FGrpcContextHandle Handle;
	UFaucetService::FTimeUntilDripResponseLambda ResponseLambda;
};

UCLASS()
class UFaucetServiceGetLinkedTwittersLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UFaucetServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetGetLinkedTwittersResponse& Response);
public:
	FGrpcContextHandle Handle;
	UFaucetService::FGetLinkedTwittersResponseLambda ResponseLambda;
};

UCLASS()
class UFaucetServiceGetLinkedTwitterForAddressLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UFaucetServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetLinkedTwitterForAddressResponse& Response);
public:
	FGrpcContextHandle Handle;
	UFaucetService::FGetLinkedTwitterForAddressResponseLambda ResponseLambda;
};

UCLASS()
class UFaucetServiceGetLinkedAddressForTwitterLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UFaucetServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetLinkedAddressForTwitterResponse& Response);
public:
	FGrpcContextHandle Handle;
	UFaucetService::FGetLinkedAddressForTwitterResponseLambda ResponseLambda;
};

UCLASS()
class UFaucetServiceSetLinkedTwitterLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UFaucetServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetSetLinkedTwitterResponse& Response);
public:
	FGrpcContextHandle Handle;
	UFaucetService::FSetLinkedTwitterResponseLambda ResponseLambda;
};

