//Generated by TurboLink CodeGenerator, do not edit!
#include "SEcsstream/EcsStreamMessage.h"
#include "SEcsstream/EcsStreamMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcEcsstreamTxMetadata, ::ecsstream::TxMetadata)
DEFINE_JSON_FUNCTIONS(FGrpcEcsstreamECSEvent, ::ecsstream::ECSEvent)
DEFINE_JSON_FUNCTIONS(FGrpcEcsstreamECSStreamBlockBundleRequest, ::ecsstream::ECSStreamBlockBundleRequest)
DEFINE_JSON_FUNCTIONS(FGrpcEcsstreamECSStreamBlockBundleReply, ::ecsstream::ECSStreamBlockBundleReply)

