//Generated by TurboLink CodeGenerator, do not edit!
#include "EcsStreamService_Private.h"

void UECSStreamServiceSubscribeToStreamLatestLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcEcsstreamECSStreamBlockBundleReply& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
}

void UECSStreamServiceSubscribeToStreamLatestLambdaWrapper::OnContextStateChanged(FGrpcContextHandle _Handle, EGrpcContextState NewState)
{
	if (_Handle != this->Handle) return;
	if (NewState == EGrpcContextState::Done)
	{
		FinishLambda();

		InnerClient->OnSubscribeToStreamLatestResponse.RemoveDynamic(this, &UECSStreamServiceSubscribeToStreamLatestLambdaWrapper::OnResponse);
		InnerClient->OnContextStateChange.RemoveDynamic(this, &UECSStreamServiceSubscribeToStreamLatestLambdaWrapper::OnContextStateChanged);
	}
}

