//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "ModeMessage.generated.h"

UENUM(BlueprintType, meta = (DisplayName="Mode.ProjectedField._rename"))
enum class EGrpcModeProjectedField_rename : uint8
{
    Rename=0,
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.Row"))
struct FGrpcModeRow : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FBytes> Values;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.GenericTable"))
struct FGrpcModeGenericTable : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FString> Cols;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcModeRow> Rows;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FString> Types;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.QueryLayerResponse"))
struct FGrpcModeQueryLayerResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TMap<FString, FGrpcModeGenericTable> Tables;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.QueryLayerStateResponse"))
struct FGrpcModeQueryLayerStateResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TMap<FString, FGrpcModeGenericTable> ChainTables;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TMap<FString, FGrpcModeGenericTable> WorldTables;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.QueryLayerStateStreamResponse"))
struct FGrpcModeQueryLayerStateStreamResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeQueryLayerStateResponse Inserted;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeQueryLayerStateResponse Updated;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeQueryLayerStateResponse Deleted;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.Namespace"))
struct FGrpcModeNamespace : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ChainId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString WorldAddress = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.StateRequest"))
struct FGrpcModeStateRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeNamespace Namespace;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FString> WorldTables;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FString> ChainTables;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.Single__StateRequest",
    HasNativeMake = "TurboLinkGrpc.GrpcModeSingle__StateRequestHelperLibrary.MakeSingle__StateRequest",
    HasNativeBreak = "TurboLinkGrpc.GrpcModeSingle__StateRequestHelperLibrary.BreakSingle__StateRequest"))
struct FGrpcModeSingle__StateRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeNamespace Namespace;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Table = "";

    TArray<TSharedPtr<FGrpcModeFilter>> Filter;

    TArray<TSharedPtr<FGrpcModeProjectedField>> Project;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.FindRequest",
    HasNativeMake = "TurboLinkGrpc.GrpcModeFindRequestHelperLibrary.MakeFindRequest",
    HasNativeBreak = "TurboLinkGrpc.GrpcModeFindRequestHelperLibrary.BreakFindRequest"))
struct FGrpcModeFindRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString From = "";

    TArray<TSharedPtr<FGrpcModeFilter>> Filter;

    TArray<TSharedPtr<FGrpcModeProjectedField>> Project;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeNamespace Namespace;

    TSharedPtr<FGrpcModeFindRequestOptions> Options;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.FindAllRequest",
    HasNativeMake = "TurboLinkGrpc.GrpcModeFindAllRequestHelperLibrary.MakeFindAllRequest",
    HasNativeBreak = "TurboLinkGrpc.GrpcModeFindAllRequestHelperLibrary.BreakFindAllRequest"))
struct FGrpcModeFindAllRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FString> Tables;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeNamespace Namespace;

    TSharedPtr<FGrpcModeFindRequestOptions> Options;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.JoinRequest",
    HasNativeMake = "TurboLinkGrpc.GrpcModeJoinRequestHelperLibrary.MakeJoinRequest",
    HasNativeBreak = "TurboLinkGrpc.GrpcModeJoinRequestHelperLibrary.BreakJoinRequest"))
struct FGrpcModeJoinRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    TSharedPtr<FGrpcModeFieldPair> On;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcModeFindRequest> Children;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeNamespace Namespace;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.DeleteRequest",
    HasNativeMake = "TurboLinkGrpc.GrpcModeDeleteRequestHelperLibrary.MakeDeleteRequest",
    HasNativeBreak = "TurboLinkGrpc.GrpcModeDeleteRequestHelperLibrary.BreakDeleteRequest"))
struct FGrpcModeDeleteRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString From = "";

    TArray<TSharedPtr<FGrpcModeFilter>> Filter;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.UpdateRequest",
    HasNativeMake = "TurboLinkGrpc.GrpcModeUpdateRequestHelperLibrary.MakeUpdateRequest",
    HasNativeBreak = "TurboLinkGrpc.GrpcModeUpdateRequestHelperLibrary.BreakUpdateRequest"))
struct FGrpcModeUpdateRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Target = "";

    TArray<TSharedPtr<FGrpcModeFilter>> Filter;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TMap<FString, FString> Row;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.InsertRequest"))
struct FGrpcModeInsertRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Into = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TMap<FString, FString> Row;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.CreateRequest"))
struct FGrpcModeCreateRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.FindRequestOptions"))
struct FGrpcModeFindRequestOptions : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Compressed = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Group = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Negate = false;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.Field"))
struct FGrpcModeField : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString TableName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString TableField = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.FieldPair"))
struct FGrpcModeFieldPair : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeField Field1;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeField Field2;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.ProjectedField._rename",
    HasNativeMake = "TurboLinkGrpc.GrpcModeProjectedField_renameHelperLibrary.Make_rename",
    HasNativeBreak = "TurboLinkGrpc.GrpcModeProjectedField_renameHelperLibrary.Break_rename"))
struct FGrpcModeProjectedField_rename : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcModeProjectedField_rename _renameCase;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Rename = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.ProjectedField"))
struct FGrpcModeProjectedField : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeField Field;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeProjectedField_rename _rename;
};

USTRUCT(BlueprintType, meta = (DisplayName="Mode.Filter"))
struct FGrpcModeFilter : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcModeField Field;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Operator = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Value = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Function = "";
};

UCLASS()
class UGrpcModeSingle__StateRequestHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static FGrpcModeSingle__StateRequest MakeSingle__StateRequest( 
        FGrpcModeNamespace Namespace, FString Table, TArray<FGrpcModeFilter> Filter, 
        TArray<FGrpcModeProjectedField> Project 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static void BreakSingle__StateRequest(const FGrpcModeSingle__StateRequest& Single__StateRequest,  
        FGrpcModeNamespace& Namespace, FString& Table, TArray<FGrpcModeFilter>& Filter, 
        TArray<FGrpcModeProjectedField>& Project 
    );
};

UCLASS()
class UGrpcModeFindRequestHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static FGrpcModeFindRequest MakeFindRequest( 
        FString From, TArray<FGrpcModeFilter> Filter, TArray<FGrpcModeProjectedField> Project, 
        FGrpcModeNamespace Namespace, FGrpcModeFindRequestOptions Options 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static void BreakFindRequest(const FGrpcModeFindRequest& FindRequest,  
        FString& From, TArray<FGrpcModeFilter>& Filter, TArray<FGrpcModeProjectedField>& Project, 
        FGrpcModeNamespace& Namespace, FGrpcModeFindRequestOptions& Options 
    );
};

UCLASS()
class UGrpcModeFindAllRequestHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static FGrpcModeFindAllRequest MakeFindAllRequest( 
        TArray<FString> Tables, FGrpcModeNamespace Namespace, FGrpcModeFindRequestOptions Options 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static void BreakFindAllRequest(const FGrpcModeFindAllRequest& FindAllRequest,  
        TArray<FString>& Tables, FGrpcModeNamespace& Namespace, FGrpcModeFindRequestOptions& Options 
    );
};

UCLASS()
class UGrpcModeJoinRequestHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static FGrpcModeJoinRequest MakeJoinRequest( 
        FGrpcModeFieldPair On, TArray<FGrpcModeFindRequest> Children, FGrpcModeNamespace Namespace 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static void BreakJoinRequest(const FGrpcModeJoinRequest& JoinRequest,  
        FGrpcModeFieldPair& On, TArray<FGrpcModeFindRequest>& Children, FGrpcModeNamespace& Namespace 
    );
};

UCLASS()
class UGrpcModeDeleteRequestHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static FGrpcModeDeleteRequest MakeDeleteRequest( 
        FString From, TArray<FGrpcModeFilter> Filter 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static void BreakDeleteRequest(const FGrpcModeDeleteRequest& DeleteRequest,  
        FString& From, TArray<FGrpcModeFilter>& Filter 
    );
};

UCLASS()
class UGrpcModeUpdateRequestHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static FGrpcModeUpdateRequest MakeUpdateRequest( 
        FString Target, TArray<FGrpcModeFilter> Filter, TMap<FString, FString> Row 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static void BreakUpdateRequest(const FGrpcModeUpdateRequest& UpdateRequest,  
        FString& Target, TArray<FGrpcModeFilter>& Filter, TMap<FString, FString>& Row 
    );
};

UCLASS()
class UGrpcModeProjectedField_renameHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static FGrpcModeProjectedField_rename Make_rename(EGrpcModeProjectedField_rename _renameCase, 
        FString Rename 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Mode", meta=(BlueprintThreadSafe))
    static void Break_rename(const FGrpcModeProjectedField_rename& _rename, EGrpcModeProjectedField_rename& _renameCase, 
        FString& Rename 
    );
};
