//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SMode/ModeService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "mode.grpc.pb.h"
#include "ModeService_Private.generated.h"

class UQueryLayer::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::mode::QueryLayer::Stub> Stub;
};

UCLASS()
class UQueryLayerGetStateLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UQueryLayerClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateResponse& Response);
public:
	FGrpcContextHandle Handle;
	UQueryLayer::FGetStateResponseLambda ResponseLambda;
};

UCLASS()
class UQueryLayerStreamStateLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UQueryLayerClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateStreamResponse& Response);
	UFUNCTION()
	void OnContextStateChanged(FGrpcContextHandle Handle, EGrpcContextState NewState);
public:
	FGrpcContextHandle Handle;
	UQueryLayer::FStreamStateResponseLambda ResponseLambda;
	UQueryLayer::FStreamStateFinishLambda FinishLambda;
};

UCLASS()
class UQueryLayerSingle__GetStateLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UQueryLayerClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateResponse& Response);
public:
	FGrpcContextHandle Handle;
	UQueryLayer::FSingle__GetStateResponseLambda ResponseLambda;
};

UCLASS()
class UQueryLayerSingle__StreamStateLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UQueryLayerClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateStreamResponse& Response);
	UFUNCTION()
	void OnContextStateChanged(FGrpcContextHandle Handle, EGrpcContextState NewState);
public:
	FGrpcContextHandle Handle;
	UQueryLayer::FSingle__StreamStateResponseLambda ResponseLambda;
	UQueryLayer::FSingle__StreamStateFinishLambda FinishLambda;
};

