//Generated by TurboLink CodeGenerator, do not edit!
#include "SEcssnapshot/EcsSnapshotMessage.h"
#include "SEcssnapshot/EcsSnapshotMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcEcssnapshotECSState, ::ecssnapshot::ECSState)
DEFINE_JSON_FUNCTIONS(FGrpcEcssnapshotECSStateSnapshot, ::ecssnapshot::ECSStateSnapshot)
DEFINE_JSON_FUNCTIONS(FGrpcEcssnapshotWorlds, ::ecssnapshot::Worlds)
DEFINE_JSON_FUNCTIONS(FGrpcEcssnapshotECSStateRequestLatest, ::ecssnapshot::ECSStateRequestLatest)
DEFINE_JSON_FUNCTIONS(FGrpcEcssnapshotECSStateRequestLatestStreamPruned, ::ecssnapshot::ECSStateRequestLatestStreamPruned)
DEFINE_JSON_FUNCTIONS(FGrpcEcssnapshotECSStateRequestLatestStream, ::ecssnapshot::ECSStateRequestLatestStream)
DEFINE_JSON_FUNCTIONS(FGrpcEcssnapshotECSStateBlockRequestLatest, ::ecssnapshot::ECSStateBlockRequestLatest)
DEFINE_JSON_FUNCTIONS(FGrpcEcssnapshotECSStateRequestAtBlock, ::ecssnapshot::ECSStateRequestAtBlock)
DEFINE_JSON_FUNCTIONS(FGrpcEcssnapshotWorldsRequest, ::ecssnapshot::WorldsRequest)
DEFINE_JSON_FUNCTIONS(FGrpcEcssnapshotECSStateReply, ::ecssnapshot::ECSStateReply)
DEFINE_JSON_FUNCTIONS(FGrpcEcssnapshotECSStateReplyV2, ::ecssnapshot::ECSStateReplyV2)
DEFINE_JSON_FUNCTIONS(FGrpcEcssnapshotECSStateBlockReply, ::ecssnapshot::ECSStateBlockReply)

