//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "CoreMinimal.h"
#include "Kismet/BlueprintAsyncActionBase.h"
#include "TurboLinkGrpcClient.h"
#include "ModeMessage.h"
#include "ModeNode.generated.h"

class UQueryLayer;
class UQueryLayerClient;

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallQueryLayerGetState : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FQueryLayerGetStateDelegate, const FGrpcResult&, GrpcResult, const FGrpcModeQueryLayerStateResponse&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call QueryLayer GetState"), Category = "TurboLink|QueryLayer")
	static UCallQueryLayerGetState* GetState(UObject* WorldContextObject, const FGrpcModeStateRequest& Request);

	UPROPERTY(BlueprintAssignable)
	FQueryLayerGetStateDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FQueryLayerGetStateDelegate OnFail;

private:
	UPROPERTY()
	UQueryLayer* QueryLayer;
	
	UPROPERTY()
	UQueryLayerClient* QueryLayerClient;
	
	FGrpcContextHandle Context;
	FGrpcModeStateRequest Request;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallQueryLayerSingle__GetState : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FQueryLayerSingle__GetStateDelegate, const FGrpcResult&, GrpcResult, const FGrpcModeQueryLayerStateResponse&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call QueryLayer Single__GetState"), Category = "TurboLink|QueryLayer")
	static UCallQueryLayerSingle__GetState* Single__GetState(UObject* WorldContextObject, const FGrpcModeSingle__StateRequest& Request);

	UPROPERTY(BlueprintAssignable)
	FQueryLayerSingle__GetStateDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FQueryLayerSingle__GetStateDelegate OnFail;

private:
	UPROPERTY()
	UQueryLayer* QueryLayer;
	
	UPROPERTY()
	UQueryLayerClient* QueryLayerClient;
	
	FGrpcContextHandle Context;
	FGrpcModeSingle__StateRequest Request;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateResponse& Response);

	void Shutdown();
};
