//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SMode/ModeMessage.h"
#include "ModeClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnQueryLayerGetStateResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcModeQueryLayerStateResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnQueryLayerStreamStateResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcModeQueryLayerStateStreamResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnQueryLayerSingle__GetStateResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcModeQueryLayerStateResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnQueryLayerSingle__StreamStateResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcModeQueryLayerStateStreamResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UQueryLayerClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnQueryLayerGetStateResponse OnGetStateResponse;

	UPROPERTY(BlueprintAssignable)
	FOnQueryLayerStreamStateResponse OnStreamStateResponse;

	UPROPERTY(BlueprintAssignable)
	FOnQueryLayerSingle__GetStateResponse OnSingle__GetStateResponse;

	UPROPERTY(BlueprintAssignable)
	FOnQueryLayerSingle__StreamStateResponse OnSingle__StreamStateResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetState();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void GetState(FGrpcContextHandle Handle, const FGrpcModeStateRequest& Request);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitStreamState();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void StreamState(FGrpcContextHandle Handle, const FGrpcModeStateRequest& Request);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitSingle__GetState();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void Single__GetState(FGrpcContextHandle Handle, const FGrpcModeSingle__StateRequest& Request);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitSingle__StreamState();

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void Single__StreamState(FGrpcContextHandle Handle, const FGrpcModeSingle__StateRequest& Request);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

