//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcService.h"
#include "SMode/ModeClient.h"
#include "ModeService.generated.h"

class UTurboLinkGrpcManager;

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UQueryLayer : public UGrpcService
{
	GENERATED_BODY()
public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual void Connect() override;
	
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual EGrpcServiceState GetServiceState() const override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	UQueryLayerClient* MakeClient();

private:
	virtual void Shutdown() override;

	UPROPERTY()
	UQueryLayerClient* InnerClient; 
public:
	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateResponse& Response)> FGetStateResponseLambda;
	void CallGetState(const FGrpcModeStateRequest& Request, FGetStateResponseLambda ResponseLambda);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateStreamResponse& Response)> FStreamStateResponseLambda;
	typedef TFunction<void()> FStreamStateFinishLambda;
	void CallStreamState(const FGrpcModeStateRequest& Request, FStreamStateResponseLambda ResponseLambda, FStreamStateFinishLambda FinishLambda);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateResponse& Response)> FSingle__GetStateResponseLambda;
	void CallSingle__GetState(const FGrpcModeSingle__StateRequest& Request, FSingle__GetStateResponseLambda ResponseLambda);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateStreamResponse& Response)> FSingle__StreamStateResponseLambda;
	typedef TFunction<void()> FSingle__StreamStateFinishLambda;
	void CallSingle__StreamState(const FGrpcModeSingle__StateRequest& Request, FSingle__StreamStateResponseLambda ResponseLambda, FSingle__StreamStateFinishLambda FinishLambda);

public:
	class Private;
	Private* const d = nullptr;

public:
	UQueryLayer();
	virtual ~UQueryLayer();
};

