//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "EcsRelayMessage.generated.h"

USTRUCT(BlueprintType, meta = (DisplayName="Ecsrelay.Identity"))
struct FGrpcEcsrelayIdentity : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsrelay.Signature"))
struct FGrpcEcsrelaySignature : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Signature = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsrelay.Message"))
struct FGrpcEcsrelayMessage : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt32 Version = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Id = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FBytes Data;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int64 Timestamp = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Signature = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsrelay.SubscriptionRequest",
    HasNativeMake = "TurboLinkGrpc.GrpcEcsrelaySubscriptionRequestHelperLibrary.MakeSubscriptionRequest",
    HasNativeBreak = "TurboLinkGrpc.GrpcEcsrelaySubscriptionRequestHelperLibrary.BreakSubscriptionRequest"))
struct FGrpcEcsrelaySubscriptionRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcEcsrelaySignature Signature;

    TSharedPtr<FGrpcEcsrelaySubscription> Subscription;
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsrelay.Subscription"))
struct FGrpcEcsrelaySubscription : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Label = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsrelay.PushRequest"))
struct FGrpcEcsrelayPushRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Label = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcEcsrelayMessage Message;
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsrelay.PushManyRequest"))
struct FGrpcEcsrelayPushManyRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcEcsrelaySignature Signature;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Label = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcEcsrelayMessage> Messages;
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsrelay.PushResponse"))
struct FGrpcEcsrelayPushResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsrelay.CountIdentitiesRequest"))
struct FGrpcEcsrelayCountIdentitiesRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsrelay.CountIdentitiesResponse"))
struct FGrpcEcsrelayCountIdentitiesResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt32 Count = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsrelay.BalanceRequest"))
struct FGrpcEcsrelayBalanceRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsrelay.BalanceResponse"))
struct FGrpcEcsrelayBalanceResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 Wei = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FDouble64 Ether = 0;
};

UCLASS()
class UGrpcEcsrelaySubscriptionRequestHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Ecsrelay", meta=(BlueprintThreadSafe))
    static FGrpcEcsrelaySubscriptionRequest MakeSubscriptionRequest( 
        FGrpcEcsrelaySignature Signature, FGrpcEcsrelaySubscription Subscription 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Ecsrelay", meta=(BlueprintThreadSafe))
    static void BreakSubscriptionRequest(const FGrpcEcsrelaySubscriptionRequest& SubscriptionRequest,  
        FGrpcEcsrelaySignature& Signature, FGrpcEcsrelaySubscription& Subscription 
    );
};
