//Generated by TurboLink CodeGenerator, do not edit!
#include "ModeService_Private.h"

void UQueryLayerGetStateLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetStateResponse.RemoveDynamic(this, &UQueryLayerGetStateLambdaWrapper::OnResponse);
}

void UQueryLayerStreamStateLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateStreamResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
}

void UQueryLayerStreamStateLambdaWrapper::OnContextStateChanged(FGrpcContextHandle _Handle, EGrpcContextState NewState)
{
	if (_Handle != this->Handle) return;
	if (NewState == EGrpcContextState::Done)
	{
		FinishLambda();

		InnerClient->OnStreamStateResponse.RemoveDynamic(this, &UQueryLayerStreamStateLambdaWrapper::OnResponse);
		InnerClient->OnContextStateChange.RemoveDynamic(this, &UQueryLayerStreamStateLambdaWrapper::OnContextStateChanged);
	}
}

void UQueryLayerSingle__GetStateLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnSingle__GetStateResponse.RemoveDynamic(this, &UQueryLayerSingle__GetStateLambdaWrapper::OnResponse);
}

void UQueryLayerSingle__StreamStateLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcModeQueryLayerStateStreamResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
}

void UQueryLayerSingle__StreamStateLambdaWrapper::OnContextStateChanged(FGrpcContextHandle _Handle, EGrpcContextState NewState)
{
	if (_Handle != this->Handle) return;
	if (NewState == EGrpcContextState::Done)
	{
		FinishLambda();

		InnerClient->OnSingle__StreamStateResponse.RemoveDynamic(this, &UQueryLayerSingle__StreamStateLambdaWrapper::OnResponse);
		InnerClient->OnContextStateChange.RemoveDynamic(this, &UQueryLayerSingle__StreamStateLambdaWrapper::OnContextStateChanged);
	}
}

