//Generated by TurboLink CodeGenerator, do not edit!
#include "SMode/ModeMessage.h"
#include "TurboLinkGrpcContext.h"
#include "mode.pb.h"

void GRPC_TO_TURBOLINK(const ::mode::Row* in, FGrpcModeRow* out);
void TURBOLINK_TO_GRPC(const FGrpcModeRow* in, ::mode::Row* out);

void GRPC_TO_TURBOLINK(const ::mode::GenericTable* in, FGrpcModeGenericTable* out);
void TURBOLINK_TO_GRPC(const FGrpcModeGenericTable* in, ::mode::GenericTable* out);

void GRPC_TO_TURBOLINK(const ::mode::QueryLayerResponse* in, FGrpcModeQueryLayerResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcModeQueryLayerResponse* in, ::mode::QueryLayerResponse* out);

void GRPC_TO_TURBOLINK(const ::mode::QueryLayerStateResponse* in, FGrpcModeQueryLayerStateResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcModeQueryLayerStateResponse* in, ::mode::QueryLayerStateResponse* out);

void GRPC_TO_TURBOLINK(const ::mode::QueryLayerStateStreamResponse* in, FGrpcModeQueryLayerStateStreamResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcModeQueryLayerStateStreamResponse* in, ::mode::QueryLayerStateStreamResponse* out);

void GRPC_TO_TURBOLINK(const ::mode::Namespace* in, FGrpcModeNamespace* out);
void TURBOLINK_TO_GRPC(const FGrpcModeNamespace* in, ::mode::Namespace* out);

void GRPC_TO_TURBOLINK(const ::mode::StateRequest* in, FGrpcModeStateRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcModeStateRequest* in, ::mode::StateRequest* out);

void GRPC_TO_TURBOLINK(const ::mode::Single__StateRequest* in, FGrpcModeSingle__StateRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcModeSingle__StateRequest* in, ::mode::Single__StateRequest* out);

void GRPC_TO_TURBOLINK(const ::mode::FindRequest* in, FGrpcModeFindRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcModeFindRequest* in, ::mode::FindRequest* out);

void GRPC_TO_TURBOLINK(const ::mode::FindAllRequest* in, FGrpcModeFindAllRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcModeFindAllRequest* in, ::mode::FindAllRequest* out);

void GRPC_TO_TURBOLINK(const ::mode::JoinRequest* in, FGrpcModeJoinRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcModeJoinRequest* in, ::mode::JoinRequest* out);

void GRPC_TO_TURBOLINK(const ::mode::DeleteRequest* in, FGrpcModeDeleteRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcModeDeleteRequest* in, ::mode::DeleteRequest* out);

void GRPC_TO_TURBOLINK(const ::mode::UpdateRequest* in, FGrpcModeUpdateRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcModeUpdateRequest* in, ::mode::UpdateRequest* out);

void GRPC_TO_TURBOLINK(const ::mode::InsertRequest* in, FGrpcModeInsertRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcModeInsertRequest* in, ::mode::InsertRequest* out);

void GRPC_TO_TURBOLINK(const ::mode::CreateRequest* in, FGrpcModeCreateRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcModeCreateRequest* in, ::mode::CreateRequest* out);

void GRPC_TO_TURBOLINK(const ::mode::FindRequestOptions* in, FGrpcModeFindRequestOptions* out);
void TURBOLINK_TO_GRPC(const FGrpcModeFindRequestOptions* in, ::mode::FindRequestOptions* out);

void GRPC_TO_TURBOLINK(const ::mode::Field* in, FGrpcModeField* out);
void TURBOLINK_TO_GRPC(const FGrpcModeField* in, ::mode::Field* out);

void GRPC_TO_TURBOLINK(const ::mode::FieldPair* in, FGrpcModeFieldPair* out);
void TURBOLINK_TO_GRPC(const FGrpcModeFieldPair* in, ::mode::FieldPair* out);

void GRPC_TO_TURBOLINK(const ::mode::ProjectedField* in, FGrpcModeProjectedField* out);
void TURBOLINK_TO_GRPC(const FGrpcModeProjectedField* in, ::mode::ProjectedField* out);

void GRPC_TO_TURBOLINK(const ::mode::Filter* in, FGrpcModeFilter* out);
void TURBOLINK_TO_GRPC(const FGrpcModeFilter* in, ::mode::Filter* out);

typedef grpc::ClientAsyncResponseReader<::mode::QueryLayerStateResponse> QueryLayer_GetState_ReaderWriter;
typedef grpc::ClientAsyncReader<::mode::QueryLayerStateStreamResponse> QueryLayer_StreamState_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::mode::QueryLayerStateResponse> QueryLayer_Single__GetState_ReaderWriter;
typedef grpc::ClientAsyncReader<::mode::QueryLayerStateStreamResponse> QueryLayer_Single__StreamState_ReaderWriter;
