//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "EcsStreamMessage.generated.h"

USTRUCT(BlueprintType, meta = (DisplayName="Ecsstream.TxMetadata"))
struct FGrpcEcsstreamTxMetadata : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString To = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FBytes Data;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt64 Value = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsstream.ECSEvent"))
struct FGrpcEcsstreamECSEvent : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString EventType = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ComponentId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString EntityId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FBytes Value;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString TxHash = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcEcsstreamTxMetadata TxMetadata;
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsstream.ECSStreamBlockBundleRequest"))
struct FGrpcEcsstreamECSStreamBlockBundleRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString WorldAddress = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool BlockNumber = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool BlockHash = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool BlockTimestamp = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool TransactionsConfirmed = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool EcsEvents = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool EcsEventsIncludeTxMetadata = false;
};

USTRUCT(BlueprintType, meta = (DisplayName="Ecsstream.ECSStreamBlockBundleReply"))
struct FGrpcEcsstreamECSStreamBlockBundleReply : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt32 BlockNumber = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString BlockHash = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt32 BlockTimestamp = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FString> TransactionsConfirmed;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcEcsstreamECSEvent> EcsEvents;
};
