//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcService.h"
#include "SEcsstream/EcsStreamClient.h"
#include "EcsStreamService.generated.h"

class UTurboLinkGrpcManager;

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UECSStreamService : public UGrpcService
{
	GENERATED_BODY()
public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual void Connect() override;
	
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual EGrpcServiceState GetServiceState() const override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	UECSStreamServiceClient* MakeClient();

private:
	virtual void Shutdown() override;

	UPROPERTY()
	UECSStreamServiceClient* InnerClient; 
public:
	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcEcsstreamECSStreamBlockBundleReply& Response)> FSubscribeToStreamLatestResponseLambda;
	typedef TFunction<void()> FSubscribeToStreamLatestFinishLambda;
	void CallSubscribeToStreamLatest(const FGrpcEcsstreamECSStreamBlockBundleRequest& Request, FSubscribeToStreamLatestResponseLambda ResponseLambda, FSubscribeToStreamLatestFinishLambda FinishLambda);

public:
	class Private;
	Private* const d = nullptr;

public:
	UECSStreamService();
	virtual ~UECSStreamService();
};

