//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SEcssnapshot/EcsSnapshotService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "ecs_snapshot.grpc.pb.h"
#include "EcsSnapshotService_Private.generated.h"

class UECSStateSnapshotService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::ecssnapshot::ECSStateSnapshotService::Stub> Stub;
};

UCLASS()
class UECSStateSnapshotServiceGetStateLatestLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcEcssnapshotECSStateReply& Response);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateLatestResponseLambda ResponseLambda;
};

UCLASS()
class UECSStateSnapshotServiceGetStateLatestStreamLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcEcssnapshotECSStateReply& Response);
	UFUNCTION()
	void OnContextStateChanged(FGrpcContextHandle Handle, EGrpcContextState NewState);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateLatestStreamResponseLambda ResponseLambda;
	UECSStateSnapshotService::FGetStateLatestStreamFinishLambda FinishLambda;
};

UCLASS()
class UECSStateSnapshotServiceGetStateLatestStreamV2LambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcEcssnapshotECSStateReplyV2& Response);
	UFUNCTION()
	void OnContextStateChanged(FGrpcContextHandle Handle, EGrpcContextState NewState);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateLatestStreamV2ResponseLambda ResponseLambda;
	UECSStateSnapshotService::FGetStateLatestStreamV2FinishLambda FinishLambda;
};

UCLASS()
class UECSStateSnapshotServiceGetStateLatestStreamPrunedLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcEcssnapshotECSStateReply& Response);
	UFUNCTION()
	void OnContextStateChanged(FGrpcContextHandle Handle, EGrpcContextState NewState);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateLatestStreamPrunedResponseLambda ResponseLambda;
	UECSStateSnapshotService::FGetStateLatestStreamPrunedFinishLambda FinishLambda;
};

UCLASS()
class UECSStateSnapshotServiceGetStateLatestStreamPrunedV2LambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcEcssnapshotECSStateReplyV2& Response);
	UFUNCTION()
	void OnContextStateChanged(FGrpcContextHandle Handle, EGrpcContextState NewState);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateLatestStreamPrunedV2ResponseLambda ResponseLambda;
	UECSStateSnapshotService::FGetStateLatestStreamPrunedV2FinishLambda FinishLambda;
};

UCLASS()
class UECSStateSnapshotServiceGetStateBlockLatestLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcEcssnapshotECSStateBlockReply& Response);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateBlockLatestResponseLambda ResponseLambda;
};

UCLASS()
class UECSStateSnapshotServiceGetStateAtBlockLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcEcssnapshotECSStateReply& Response);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetStateAtBlockResponseLambda ResponseLambda;
};

UCLASS()
class UECSStateSnapshotServiceGetWorldsLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UECSStateSnapshotServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcEcssnapshotWorlds& Response);
public:
	FGrpcContextHandle Handle;
	UECSStateSnapshotService::FGetWorldsResponseLambda ResponseLambda;
};

