//Generated by TurboLink CodeGenerator, do not edit!
#include "FaucetService_Private.h"

void UFaucetServiceDripLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetDripResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnDripResponse.RemoveDynamic(this, &UFaucetServiceDripLambdaWrapper::OnResponse);
}

void UFaucetServiceDripDevLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetDripResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnDripDevResponse.RemoveDynamic(this, &UFaucetServiceDripDevLambdaWrapper::OnResponse);
}

void UFaucetServiceDripVerifyTweetLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetDripResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnDripVerifyTweetResponse.RemoveDynamic(this, &UFaucetServiceDripVerifyTweetLambdaWrapper::OnResponse);
}

void UFaucetServiceTimeUntilDripLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetTimeUntilDripResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnTimeUntilDripResponse.RemoveDynamic(this, &UFaucetServiceTimeUntilDripLambdaWrapper::OnResponse);
}

void UFaucetServiceGetLinkedTwittersLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetGetLinkedTwittersResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetLinkedTwittersResponse.RemoveDynamic(this, &UFaucetServiceGetLinkedTwittersLambdaWrapper::OnResponse);
}

void UFaucetServiceGetLinkedTwitterForAddressLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetLinkedTwitterForAddressResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetLinkedTwitterForAddressResponse.RemoveDynamic(this, &UFaucetServiceGetLinkedTwitterForAddressLambdaWrapper::OnResponse);
}

void UFaucetServiceGetLinkedAddressForTwitterLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetLinkedAddressForTwitterResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetLinkedAddressForTwitterResponse.RemoveDynamic(this, &UFaucetServiceGetLinkedAddressForTwitterLambdaWrapper::OnResponse);
}

void UFaucetServiceSetLinkedTwitterLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcFaucetSetLinkedTwitterResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnSetLinkedTwitterResponse.RemoveDynamic(this, &UFaucetServiceSetLinkedTwitterLambdaWrapper::OnResponse);
}

